apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 6
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: rf1996/test-react:v1
        name: guestbook-ui
        resources:
          limit:
            cpu: 0.5
            memory: 0.5Gi
          request:
            cpu: 0.25
            memory: 0.25Gi
        ports:
        - containerPort: 80
